[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Services", "Win32_System_SystemServices", "Win32_System_Wmi", "Win32_NetworkManagement_WindowsFilteringPlatform", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi"] }
ring = "0.17.14"
aes-gcm = "0.10.3"
rsa = "0.9.10"
sha2 = "0.11.0"
sysinfo = "0.38.4"
uuid = { version = "1.23.1", features = ["v4"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1.52.3", features = ["full"] }
reqwest = { version = "0.13.3", features = ["json"] }
base64 = "0.22.1"
hmac = "0.13.0"
pbkdf2 = "0.13.0"
hex = "0.4.3"
log = "0.4.29"
env_logger = "0.11.10"

[features]
opencv = []

[dev-dependencies]
tempfile = "3.27.0"
